const menu = [
  {
    id: 1,
    title: 'Ayam Geprek Sambal Ijo',
    category: 'ayam',
    price: 18000,
    img: './images/1.jpg',
    desc: `Ayam 1 potong + sambal ijo + lalapan + nasi`,
  },
  {
    id: 2,
    title: 'Ayam Goreng Sambal Merah',
    category: 'ayam',
    price: 18000,
    img: './images/2.jpeg',
    desc: `Ayam 1 potong + sambal merah + lalapan + nasi`,
  },
  {
    id: 3,
    title: 'Ayam Bakar Kecap',
    category: 'ayam',
    price: 19000,
    img: './images/3.jpg',
    desc: `Ayam Bakar 1 potong + lalapan + nasi`,
  },
  {
    id: 4,
    title: 'Ayam Goreng Kampung',
    category: 'ayam',
    price: 35000,
    img: './images/4.jpg',
    desc: `Ayam goreng kampung + nasi + lalapan`,
  },
  {
    id: 5,
    title: 'Bebek Goreng Sambal Ijo',
    category: 'bebek',
    price: 35000,
    img: './images/5.jpg',
    desc: `Bebek Goreng + sambal ijo + lalapan + nasi`,
  },
  {
    id: 6,
    title: 'Bebek Goreng Sambal Merah',
    category: 'bebek',
    price: 35000,
    img: './images/6.jpg',
    desc: `Bebek Goreng + sambal merah + lalapan + nasi`,
  },
  {
    id: 7,
    title: 'Terong',
    category: 'sayur',
    price: 5000,
    img: './images/7.jpg',
    desc: `Tambahan terong`,
  },
  {
    id: 8,
    title: 'Lele Goreng',
    category: 'ikan',
    price: 17000,
    img: './images/8.jpeg',
    desc: `Lele goreng + nasi + lalapan`,
  },
  {
    id: 9,
    title: 'Jaer Nila Goreng',
    category: 'ikan',
    price: 18000,
    img: './images/9.jpg',
    desc: `Ikan jaer / nila goreng + nasi + lalapan`,
  },
  {
    id: 10,
    title: 'Ikan Mas Goreng',
    category: 'ikan',
    price: 17000,
    img: './images/10.jpg',
    desc: `Ikan mas goreng + nasi + lalapan`,
  },
  {
    id: 11,
    title: 'Bawal Tawar Goreng',
    category: 'ikan',
    price: 15000,
    img: './images/11.jpg',
    desc: `Ikan bawal tawar goreng + nasi + lalapan`,
  },
  {
    id: 12,
    title: 'Kembung Banjar Goreng',
    category: 'ikan',
    price: 20000,
    img: './images/12.png',
    desc: `Ikan kembung banjar + nasi + lalapan`,
  },
  {
    id: 13,
    title: 'Ikan Barakuda Goreng',
    category: 'ikan',
    price: 30000,
    img: './images/13.jpg',
    desc: `Ikan barakuda goreng + nasi + lalapan`,
  },
  {
    id: 14,
    title: 'Gurame Goreng',
    category: 'ikan',
    price: 35000,
    img: './images/14.jpeg',
    desc: `Ikan gurame goreng + nasi + lalapan`,
  },
  {
    id: 15,
    title: 'Usus',
    category: 'lainnya',
    price: 2500,
    img: './images/15.jpg',
    desc: `Tambahan sate usus`,
  },
  {
    id: 16,
    title: 'Kulit',
    category: 'lainnya',
    price: 2500,
    img: './images/16.jpg',
    desc: `Tambahan sate kulit`,
  },
  {
    id: 17,
    title: 'Tahu/Tempe',
    category: 'lainnya',
    price: 1000,
    img: './images/17.jpg',
    desc: `Tambahan tahu/tempe`,
  },
  {
    id: 18,
    title: 'Kol Goreng',
    category: 'sayur',
    price: 3000,
    img: './images/18.jpg',
    desc: `Tambahan kol goreng`,
  },
  {
    id: 19,
    title: 'Telur (Dadar/Mata Sapi)',
    category: 'lainnya',
    price: 4000,
    img: './images/19.jpg',
    desc: `Tambahan telur dadar/mata sapi`,
  },
  {
    id: 20,
    title: 'Ati Ampela',
    category: 'lainnya',
    price: 5000,
    img: './images/20.jpg',
    desc: `Tambahan ati ampela`,
  },
  {
    id: 21,
    title: 'Cobek Kangkung',
    category: 'sayur',
    price: 6000,
    img: './images/21.jpg',
    desc: `Tambahan cobek kangkung`,
  },
  {
    id: 22,
    title: 'Belut',
    category: 'lainnya',
    price: 12000,
    img: './images/22.jpg',
    desc: `Tambahan belut`,
  },

  {
    id: 23,
    title: 'Cumi Goreng',
    category: 'lainnya',
    price: 20000,
    img: './images/23.jpeg',
    desc: `Cumi goreng + nasi + lalapan`,
  },
  {
    id: 24,
    title: 'Udang Goreng',
    category: 'lainnya',
    price: 17000,
    img: './images/24.jpg',
    desc: `Udang goreng + nasi + lalapan`,
  },
];
export default menu;
